# Generated by Django 4.2 on 2023-05-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HelloWorld", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=128, verbose_name="密码"),
        ),
    ]
