# Generated by Django 4.2 on 2023-05-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HelloWorld", "0002_alter_admin_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=64, verbose_name="密码"),
        ),
    ]
